# Generated by Django 3.0.8 on 2020-07-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
